
language: ruby
rvm: 2.6.0
sudo: false

before_install:
 - gem install hiptest-publisher
 - hiptest-publisher -c cucumber.conf --token=$SECRET_TOKEN --only=features,step_definitions --test-run-id=$TEST_RUN_ID

script:
 - bundle exec cucumber --format json --out results.json

after_script:
  - hiptest-publisher -c cucumber.conf --token=$SECRET_TOKEN --push=results.json --test-run-id=$TEST_RUN_ID
