# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: update tests with hiptest-publisher
          command: |
            echo 'export PATH=$PATH:.' >> $PATH
            gem install hiptest-publisher
            source $PATH
            hiptest-publisher --token=${SECRET_TOKEN} -c rspec.conf --test-run-id=${TEST_RUN_ID} --only=tests
      
      - run:
          name: regenerate tests and fetch UIDs
          command:
            hiptest-publisher --token=${SECRET_TOKEN} -c rspec.conf --test-run-id=${TEST_RUN_ID} --only=tests

      # run tests!
      - run:
          name: run tests
          command:
            bundle exec cucumber --format junit --out results
            
      - run:
          name: push test results file
          command:
            hiptest-publisher -c rspec.conf --token=${SECRET_TOKEN} --push="results/TEST-*.xml" --test-run-id=${TEST_RUN_ID}
